FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
# Pre-create uploads directory
RUN mkdir -p /app/uploads
COPY file-storing-service/build/libs/file-storing-service-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
